version: 0.2
phases:
   pre_build:
      commands:
      - echo "Entered the pre-build phase - Nothing to do"
   build:
      commands:
      - echo "Entered build phase"
      - mvn install
   post_build:
      commands:
      - echo echo Build completed on `date`
artifacts:
   files:
   - target/auth.jar